Repository sympy/sympy, pull requests merged in 2025-04, with the labels that each got.

#27520 Added NaN handler for NegativePredicate
  sympy/assumptions/handlers/order.py
  sympy/assumptions/tests/test_query.py
Labels: assumptions

#27884 Changed the output of `igcdex` for the all-zero case
  sympy/core/intfunc.py
  sympy/core/tests/test_numbers.py
Labels: core

#27882 maint: drop Python 3.8
  .github/workflows/emscripten.yml
  .github/workflows/release.yml
  .github/workflows/runtests.yml
  setup.py
  sympy/__init__.py
  sympy/external/ntheory.py
  sympy/parsing/tests/test_sympy_parser.py
Labels: CI

#27850 Update old type annotation syntax to new TypeHints
  .mailmap
  sympy/__init__.py
  sympy/abc.py
  sympy/codegen/ast.py
  sympy/codegen/fnodes.py
  sympy/concrete/products.py
  sympy/concrete/summations.py
  sympy/core/evalf.py
  sympy/core/exprtools.py
  sympy/external/gmpy.py
  sympy/external/pythonmpq.py
  sympy/functions/combinatorial/numbers.py
  sympy/functions/elementary/complexes.py
  sympy/functions/elementary/exponential.py
  sympy/functions/elementary/integers.py
  sympy/functions/elementary/trigonometric.py
  sympy/matrices/common.py
  sympy/matrices/dense.py
  sympy/matrices/matrixbase.py
  sympy/parsing/sympy_parser.py
  sympy/physics/units/definitions/dimension_definitions.py
  sympy/physics/units/unitsystem.py
  sympy/polys/domains/gaussiandomains.py
  sympy/polys/matrices/domainmatrix.py
  sympy/printing/printer.py
  sympy/solvers/diophantine/diophantine.py
  sympy/solvers/ode/single.py
  sympy/stats/rv.py
  sympy/stats/stochastic_process_types.py
  sympy/tensor/array/expressions/array_expressions.py
  sympy/tensor/array/expressions/from_array_to_matrix.py
  sympy/tensor/tensor.py
Labels: typing

#27741 Fix IntegerPredicate Handling for Pow and Mul Expressions
  sympy/assumptions/handlers/common.py
  sympy/assumptions/handlers/sets.py
  sympy/assumptions/tests/test_query.py
Labels: assumptions

#27896 `FURB188` has been fixed
  sympy/core/numbers.py
  sympy/printing/str.py
Labels: Code quality

#27894 Handle Sums with lower > upper limit, if ∞ is present
  .mailmap
  sympy/concrete/summations.py
  sympy/concrete/tests/test_sums_products.py
Labels: concrete

#27903 File read and write operations were updated to use `pathlib.Path`
  bin/ask_update.py
  bin/coverage_doctest.py
  doc/ext/convert-svg-to-pdf.py
  doc/generate_logos.py
  release/authors.py
  release/github_release.py
  release/sha256.py
  setup.py
  sympy/core/tests/test_args.py
  sympy/external/tests/test_autowrap.py
  sympy/external/tests/test_codegen.py
  sympy/logic/utilities/dimacs.py
  sympy/parsing/latex/lark/latex_parser.py
  sympy/parsing/tests/test_custom_latex.py
  sympy/printing/preview.py
  sympy/testing/pytest.py
  sympy/testing/runtests.py
  sympy/testing/runtests_pytest.py
  sympy/utilities/_compilation/compilation.py
  sympy/utilities/autowrap.py
  sympy/utilities/tests/test_autowrap.py
Labels: Code quality

#27904 Fix is_hermitian to correctly handle block matrices
  .mailmap
  sympy/matrices/matrixbase.py
  sympy/matrices/tests/test_matrices.py
Labels: matrices

#27905 Fix for ruff rules `FURB132` and `FURB136`
  sympy/polys/subresultants_qq_zz.py
  sympy/solvers/diophantine/diophantine.py
Labels: Code quality

#27906 Fix for ruff rule `FURB152`
  sympy/plotting/pygletplot/plot_rotation.py
  sympy/printing/aesaracode.py
  sympy/printing/theanocode.py
Labels: Code quality

#27907 Fix for ruff rules `FURB154` and `FURB156`
  .ci/parse_durations_log.py
  sympy/crypto/crypto.py
  sympy/ntheory/partitions_.py
  sympy/printing/pretty/pretty_symbology.py
  sympy/utilities/misc.py
  sympy/utilities/tests/test_enumerative.py
Labels: Code quality

#27912 Fix for ruff rule `FURB129`
  bin/mailmap_check.py
  sympy/parsing/autolev/_build_autolev_antlr.py
  sympy/parsing/latex/_build_latex_antlr.py
Labels: Code quality

#27913 Fix for ruff rules `FURB142` and `FURB148`
  sympy/core/basic.py
  sympy/core/exprtools.py
  sympy/physics/vector/dyadic.py
  sympy/physics/vector/vector.py
  sympy/tensor/array/expressions/array_expressions.py
  sympy/testing/runtests.py
Labels: Code quality

#27914 Fix for ruff rule `FURB167`
  doc/ext/docscrape.py
  doc/ext/docscrape_sphinx.py
  doc/ext/numpydoc.py
  sympy/printing/conventions.py
  sympy/printing/tests/test_smtlib.py
  sympy/testing/pytest.py
  sympy/utilities/misc.py
Labels: Code quality

#27900 [feat] Ringseries: added rs_cosh_sinh to caluclate the faster cosh, sinh series together.
  doc/src/modules/polys/ringseries.rst
  sympy/polys/puiseux.py
  sympy/polys/ring_series.py
  sympy/polys/tests/test_ring_series.py
Labels: ringseries

#27919 Update rust printer with 2018/2024 edition reserved words
  .mailmap
  sympy/printing/rust.py
Labels: printing

#27930 Fix for ruff rule `FURB145`
  sympy/combinatorics/perm_groups.py
  sympy/combinatorics/permutations.py
  sympy/combinatorics/tests/test_testutil.py
  sympy/physics/vector/frame.py
  sympy/physics/vector/point.py
  sympy/series/acceleration.py
  sympy/solvers/ode/ode.py
  sympy/tensor/tensor.py
Labels: Code quality

#27928 Raise an error for matrices with symbolic shape to prevent infinite loops.
  sympy/solvers/solvers.py
  sympy/solvers/tests/test_solvers.py
Labels: solvers.solve, matrices.expressions

#27934 Add the `FURB` rule of ruff to `pyproject.toml`
  pyproject.toml
Labels: Code quality, CI

#27943 fix(test): disable doctests that give warnings
  doc/src/explanation/active-deprecations.md
  sympy/physics/quantum/operator.py
Labels: Testing

#27942 maint(release): Use --prerelease for GH releases
  .github/workflows/release.yml
Labels: Releasing

#27933 RingSeries: Refactor `rs_` function and add missing tests for _atan, _atanh, and test_puiseux.
  sympy/polys/ring_series.py
  sympy/polys/tests/test_ring_series.py
Labels: ringseries

#27945 maint(release): fix release workflow syntax
  .github/workflows/release.yml
Labels: Releasing

#27941 maint(release): bump version to 1.15.0.dev
  .github/workflows/release.yml
  doc/src/explanation/active-deprecations.md
  sympy/release.py
Labels: Releasing

#27946 Revert "maint(release): bump version to 1.15.0.dev"
  .github/workflows/release.yml
  doc/src/explanation/active-deprecations.md
  sympy/release.py
Labels: Releasing

#27722 Add Sphinx hyperlinks for missing function references in basic_operations.rst and calculus.rst
  .mailmap
  doc/src/tutorials/intro-tutorial/basic_operations.rst
  doc/src/tutorials/intro-tutorial/calculus.rst
Labels: Documentation

#27867 fix(test_dot): correct argument order in an assert statement
  .mailmap
  sympy/vector/tests/test_vector.py
Labels: vector

#27935 printing: Deprecate aesaracode
  doc/src/contributing/dependencies.md
  doc/src/explanation/active-deprecations.md
  doc/src/explanation/modules/physics/mechanics/sympy_mechanics_for_autolev_users.rst
  doc/src/modules/codegen.rst
  doc/src/modules/numeric-computation.rst
  sympy/printing/aesaracode.py
  sympy/printing/tests/test_aesaracode.py
Labels: printing

#27949 core: deprecate Rational(2, 4, gcd=1)
  doc/src/explanation/active-deprecations.md
  sympy/core/numbers.py
  sympy/core/tests/test_numbers.py
Labels: core, core.numbers

#27940 maint(release): update AUTHORS file.
  .mailmap
  AUTHORS
Labels: Releasing

#27947 maint(release): Rebump version to 1.15.dev on master
  .github/workflows/release.yml
  doc/src/explanation/active-deprecations.md
  sympy/release.py
Labels: Releasing

#27953 maint(release): update versions on 1.14 release branch
  .github/workflows/release.yml
  .github/workflows/runtests.yml
  asv.conf.actions.json
  sympy/release.py
Labels: Releasing

#27954 maint(release): bump versions on master branch
  .github/workflows/runtests.yml
  asv.conf.actions.json
Labels: Releasing

#27955 Fix workflow syntax for github release
  .github/workflows/release.yml
Labels: Releasing

#27960 maint(release): pin mpmath < 1.4 for sympy 1.14
  .github/workflows/release.yml
  .github/workflows/runtests.yml
  setup.py
  sympy/external/gmpy.py
Labels: Releasing, mpmath

#27966 Fix for Xor operator bug in parse_expr with false evaluation
  .mailmap
  sympy/parsing/sympy_parser.py
  sympy/parsing/tests/test_sympy_parser.py
Labels: parsing

#27821 Fix unit conversion for custom quantities with non-SI reference units (e.g., ft²)
  sympy/physics/units/dimensions.py
  sympy/physics/units/tests/test_unitsystem.py
  sympy/physics/units/tests/test_util.py
Labels: physics.units

#27965 Fix: Allow multiplication of basis vectors by float zero (0.0)
  sympy/vector/basisdependent.py
  sympy/vector/tests/test_vector.py
Labels: vector

#27970 maint(ci): fix benchmarks on 1.14 branch
  .github/workflows/runtests.yml
Labels: Releasing

#27601 Reset Visited List Color to Default
  doc/src/_static/custom.css
Labels: Documentation

#27686 Fix RecursionError in ODE solver when using Float coefficients
  .github/workflows/runtests.yml
  doc/src/tutorials/intro-tutorial/solvers.rst
  sympy/solvers/ode/ode.py
  sympy/solvers/ode/single.py
  sympy/solvers/ode/tests/test_ode.py
  sympy/solvers/ode/tests/test_single.py
  sympy/solvers/tests/test_pde.py
Labels: solvers.dsolve

#27976 Remove @xfail from tests that are now passing
  sympy/sets/tests/test_powerset.py
  sympy/stats/tests/test_rv.py
  sympy/utilities/tests/test_pickling.py
  sympy/utilities/tests/test_wester.py
Labels: Testing

#27931 Fix: AttributeError for some hypergeometric expr in hypersimp
  sympy/solvers/recurr.py
  sympy/solvers/tests/test_recurr.py
Labels: simplify

#27997 Remove hermitian and antihermitian from the old assumptions system
  doc/src/guides/assumptions.rst
  sympy/core/assumptions.py
  sympy/core/assumptions_generated.py
  sympy/core/basic.py
  sympy/core/expr.py
  sympy/core/tests/test_arit.py
  sympy/core/tests/test_assumptions.py
  sympy/core/tests/test_noncommutative.py
  sympy/functions/elementary/tests/test_complexes.py
  sympy/printing/tree.py
  sympy/simplify/tests/test_simplify.py
Labels: assumptions, physics.quantum

#28004 release: bump version to 1.14.0 final
  .github/workflows/release.yml
  sympy/release.py
Labels: Releasing

#28009 Restrict the return type of `perfect_power` to `tuple[int, int]` or `False`
  sympy/core/numbers.py
  sympy/ntheory/factor_.py
Labels: ntheory, core.numbers

#27974 Faster wigner symbols implementation using `math.comb`
  .mailmap
  sympy/physics/tests/test_clebsch_gordan.py
  sympy/physics/wigner.py
Labels: physics

#28013 Handle the case of 2 separately in `factor_base` construction in `qs`
  sympy/ntheory/qs.py
  sympy/ntheory/tests/test_qs.py
Labels: ntheory

#28011 Use charpoly instead of manual calculation which is more robust to large expressions in A.
  sympy/physics/control/lti.py
Labels: physics.control
